server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ooad?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false